# Generated by Django 4.0.1 on 2022-01-25 09:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_remove_userprofile_name_remove_userprofile_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('subtitles', models.CharField(max_length=3)),
                ('subtitles_language', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 2, 24, 10, 0, 47, 260584))),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
