# Generated by Django 4.0.1 on 2022-01-25 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_movie_movierented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subtitles_language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 10, 2, 23, 815651)),
        ),
    ]
