# Generated by Django 4.0.1 on 2022-01-25 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_movie_subtitles_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subtitles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 10, 5, 40, 881713)),
        ),
    ]
