# Generated by Django 4.0.1 on 2022-01-25 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_movie_subtitles_alter_movierented_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subtitles_language',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 10, 7, 34, 264741)),
        ),
    ]
