# Generated by Django 4.0.1 on 2022-01-25 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_movie_subtitles_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 10, 10, 44, 944520)),
        ),
    ]
