# Generated by Django 4.0.1 on 2022-01-25 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_movierented_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 10, 14, 38, 92988)),
        ),
    ]
