# Generated by Django 4.0.1 on 2022-01-25 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_movie_language_alter_movierented_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('Lector', 'Lektor'), ('Original', 'Oryginalna'), ('Dubbing', 'Dubbing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 10, 29, 42, 594529)),
        ),
    ]
