# Generated by Django 4.0.1 on 2022-01-27 10:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_movie_soundtrack_alter_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='minimum_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 11, 1, 48, 302181)),
        ),
    ]
