# Generated by Django 4.0.1 on 2022-01-27 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_movierented_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='soundtrack',
            field=models.CharField(choices=[('Lektor', 'Lektor'), ('Oryginalna', 'Oryginalna'), ('Dubbing', 'Dubbing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movierented',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 13, 45, 39, 246457)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 13, 45, 39, 246456)),
        ),
    ]
